// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tsdb.proto

package tsdb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WritePointsRequest struct {
	ShardID              uint64   `protobuf:"varint,1,opt,name=shardID,proto3" json:"shardID,omitempty"`
	Points               []byte   `protobuf:"bytes,2,opt,name=points,proto3" json:"points,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WritePointsRequest) Reset()         { *m = WritePointsRequest{} }
func (m *WritePointsRequest) String() string { return proto.CompactTextString(m) }
func (*WritePointsRequest) ProtoMessage()    {}
func (*WritePointsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d338563a62b99d5, []int{0}
}

func (m *WritePointsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WritePointsRequest.Unmarshal(m, b)
}
func (m *WritePointsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WritePointsRequest.Marshal(b, m, deterministic)
}
func (m *WritePointsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WritePointsRequest.Merge(m, src)
}
func (m *WritePointsRequest) XXX_Size() int {
	return xxx_messageInfo_WritePointsRequest.Size(m)
}
func (m *WritePointsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WritePointsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WritePointsRequest proto.InternalMessageInfo

func (m *WritePointsRequest) GetShardID() uint64 {
	if m != nil {
		return m.ShardID
	}
	return 0
}

func (m *WritePointsRequest) GetPoints() []byte {
	if m != nil {
		return m.Points
	}
	return nil
}

type WritePointsReply struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WritePointsReply) Reset()         { *m = WritePointsReply{} }
func (m *WritePointsReply) String() string { return proto.CompactTextString(m) }
func (*WritePointsReply) ProtoMessage()    {}
func (*WritePointsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d338563a62b99d5, []int{1}
}

func (m *WritePointsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WritePointsReply.Unmarshal(m, b)
}
func (m *WritePointsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WritePointsReply.Marshal(b, m, deterministic)
}
func (m *WritePointsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WritePointsReply.Merge(m, src)
}
func (m *WritePointsReply) XXX_Size() int {
	return xxx_messageInfo_WritePointsReply.Size(m)
}
func (m *WritePointsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_WritePointsReply.DiscardUnknown(m)
}

var xxx_messageInfo_WritePointsReply proto.InternalMessageInfo

func (m *WritePointsReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*WritePointsRequest)(nil), "internal.WritePointsRequest")
	proto.RegisterType((*WritePointsReply)(nil), "internal.WritePointsReply")
}

func init() { proto.RegisterFile("tsdb.proto", fileDescriptor_8d338563a62b99d5) }

var fileDescriptor_8d338563a62b99d5 = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x29, 0x4e, 0x49,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xc8, 0xcc, 0x2b, 0x49, 0x2d, 0xca, 0x4b, 0xcc,
	0x51, 0x72, 0xe3, 0x12, 0x0a, 0x2f, 0xca, 0x2c, 0x49, 0x0d, 0xc8, 0xcf, 0xcc, 0x2b, 0x29, 0x0e,
	0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe0, 0x62, 0x2f, 0xce, 0x48, 0x2c, 0x4a, 0xf1,
	0x74, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x09, 0x82, 0x71, 0x85, 0xc4, 0xb8, 0xd8, 0x0a, 0xc0,
	0x4a, 0x25, 0x98, 0x14, 0x18, 0x35, 0x78, 0x82, 0xa0, 0x3c, 0x25, 0x15, 0x2e, 0x01, 0x14, 0x73,
	0x0a, 0x72, 0x2a, 0x85, 0x04, 0xb8, 0x98, 0x53, 0x8b, 0x8a, 0xc0, 0x26, 0x70, 0x06, 0x81, 0x98,
	0x46, 0x21, 0x5c, 0xec, 0x21, 0xc5, 0x29, 0x49, 0x41, 0x01, 0xce, 0x42, 0x9e, 0x5c, 0xdc, 0x48,
	0x1a, 0x84, 0x64, 0xf4, 0x60, 0x4e, 0xd2, 0xc3, 0x74, 0x8f, 0x94, 0x14, 0x0e, 0xd9, 0x82, 0x9c,
	0x4a, 0x25, 0x86, 0x24, 0x36, 0xb0, 0xa7, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x01, 0x2a,
	0xee, 0x8e, 0xe2, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TsdbRPCClient is the client API for TsdbRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TsdbRPCClient interface {
	WritePoints(ctx context.Context, in *WritePointsRequest, opts ...grpc.CallOption) (*WritePointsReply, error)
}

type tsdbRPCClient struct {
	cc *grpc.ClientConn
}

func NewTsdbRPCClient(cc *grpc.ClientConn) TsdbRPCClient {
	return &tsdbRPCClient{cc}
}

func (c *tsdbRPCClient) WritePoints(ctx context.Context, in *WritePointsRequest, opts ...grpc.CallOption) (*WritePointsReply, error) {
	out := new(WritePointsReply)
	err := c.cc.Invoke(ctx, "/internal.TsdbRPC/WritePoints", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TsdbRPCServer is the server API for TsdbRPC service.
type TsdbRPCServer interface {
	WritePoints(context.Context, *WritePointsRequest) (*WritePointsReply, error)
}

func RegisterTsdbRPCServer(s *grpc.Server, srv TsdbRPCServer) {
	s.RegisterService(&_TsdbRPC_serviceDesc, srv)
}

func _TsdbRPC_WritePoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WritePointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TsdbRPCServer).WritePoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.TsdbRPC/WritePoints",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TsdbRPCServer).WritePoints(ctx, req.(*WritePointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TsdbRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "internal.TsdbRPC",
	HandlerType: (*TsdbRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WritePoints",
			Handler:    _TsdbRPC_WritePoints_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tsdb.proto",
}
